#Created by webjeda - http://webjeda.com

title: sunx7.github.io #Keep it short
email: mybliz1@gmail.com


baseurl: /sunx7

sass:
 style: compressed
 
 
# Tracker
analytics: UA-83979019-1
 
### exclude the instructions / write-up in the README.md
exclude:
- README.md
